### ISSUE TITLE
Are autoruns expected?

### ISSUE THREAD

**Issue by aquamme** [stefanpenner/ember-fetch#12]
I'm finding that ember-fetch is consistently creating autoruns when xhr.onload or reader.onload is triggered. Is this intended? I'm encountering issues with my acceptance tests finishing and being torn down before requests finish and I'm trying to track down the cause.

**Comment by aquamme** [comment]
I figured out my test issue, but the question about autoruns remains.

**Comment by stefanpenner** [comment]
can you share an example of when this happens? Promises should be immune to auto-run assertions, because they handle it more or less correctly. Must interactions I can think of here should be as such, its possible im just missing your likely obvious scenario.

**Comment by aquamme** [comment]
To be clear - I'm not seeing any autorun assertions fail. When I was trying to track down my test issues I noticed that `createAutorun` was being called after every fetch. It sounds like this isn't a problem unless the assertion fails?

**Comment by stefanpenner** [comment]
Correct. Promises settling based on native async are blessed here, as they should absorb issues correctly.
