### ISSUE TITLE
[Question]: why no "failed to find import" message when using fetch?

### ISSUE THREAD

**Issue by toranb** [stefanpenner/ember-fetch#15]
I was doing some hacking with ember-fetch as usual this morning and spent a good deal of time looking at my mirage configuration/ other dependencies because a fetch based POST was resulting in a 404. Many hours later I finally found that my component was missing the import (and nothing more).

```import fetch from 'fetch';```

Any idea why the build didn't blow up w/out this to begin with? I wanted to see what I could do to help save others like me precious time when an import is missing like this :)

Here is the code if that helps - building with ember-cli v2.8.0 (node v5.12) and running in Chrome 54

```js
import Ember from 'ember';
import hbs from 'htmlbars-inline-precompile';
import connect from 'ember-redux/components/connect';
import _ from 'npm:lodash';
import fetch from 'fetch';

var stateToComputed = (state) => {
  return {
    result: _.get(state.results.all, state.results.selectedId)
  };
};

var dispatchToActions = (dispatch) => {
  return {
    rate: (id, rating) => fetch(`/api/results/${id}`, {method: 'POST', body: JSON.stringify({rating: rating})}).then(fetched => fetched.json()).then((response) => dispatch({type: 'RATE_ITEM', response: response.item}))
  };
};

var WelpResultComponent = Ember.Component.extend({
  layout: hbs`
    {{yield result (action "rate")}}
  `
});

export default connect(stateToComputed, dispatchToActions)(WelpResultComponent);
```

**Comment by tchak** [comment]
It did not blow up because you were using native `fetch`. I understand your frustration, but I am not sure I understand the behaviour you expected.

**Comment by toranb** [comment]
@tchak ah, didn't realize :) so it's the fact that I'm using Chrome that was the issue (assuming it supports native fetch?)

The problem would seem to be that native fetch and ember-fetch are different I assume - no immediate solution comes to mind I suppose. Mostly trying to understand if something could be done to help others
