### ISSUE TITLE
Anyone using this w/ typescript yet?

### ISSUE THREAD

**Issue by toranb** [stefanpenner/ember-fetch#33]
I'm looking around for a type def file for `ember-fetch` and thought I might give `npm install --save @types/whatwg-fetch` a look first / but during that time I wanted to see if others are already using this with TS

**Comment by toranb** [comment]
For anyone who might follow - until this is supported legit I've got a simple type defs repo up that seems to make the compiler happy for now

https://github.com/toranb/ember-fetch-tsdefs/blob/master/index.d.ts

```bash
npm install ember-fetch-tsdefs -D
```

**Comment by stefanpenner** [comment]
Is there a downside to submitting those types to this repo?

**Comment by toranb** [comment]
@stefanpenner good question .. mostly that Toran is the furthest thing from "expert types ninja" at the moment. If someone else can jump in and confirm "yup -looks legit bro" then I say we could ship it and iterate 

Here is how I'm using that btw

```js
  return fetch('/api/restaurants')
    .then((fetched: Response) => fetched.json())
    .then((response: Restaurants) => dispatch({
      type: ActionTypes.TRANSFORM_LIST,
      response: response
    }));
```

**Comment by stefanpenner** [comment]
@toranb if you have cycles to submit it as a PR, I can gladly take a look :). I'll also bug señor @krisselden (our resident guru) to review.

**Comment by toranb** [comment]
@stefanpenner it's possible - 2 questions related to submitting a PR for this

1) how does one test this? it could require we add typescript to this repo as a devDependency
2) what min version of typescript will we support? I'm using TS v2.3 right now for example

**Comment by toranb** [comment]
example of [typescript-definition-tester](https://github.com/adamcarr/typescript-definition-tester) in action 

https://github.com/gaearon/redux-thunk/pull/77/files

note: this could be considered "over kill" - worth mentioning either way

**Comment by stefanpenner** [comment]
I'll ask @krisselden to chime in.

**Comment by stefanpenner** [comment]
@toranb i suspect just running the ts validate step is sufficient for testing.

**Comment by toranb** [comment]
@stefanpenner good call boss - I'll wait to hear from @krisselden on what he thinks of these type defs :)

**Comment by toranb** [comment]
@stefanpenner closing this out for now - we can continue discussion in the PR
