### ISSUE TITLE
Fetch promises always resolving

### ISSUE THREAD

**Issue by orf** [stefanpenner/ember-fetch#35]
Hello,
I'm using Ember 2.9, and it appears that the promise returned from` fetch` always resolves, even if there is an error.

I think it's down to this line: https://github.com/stefanpenner/ember-fetch/blob/c2cbcb97a1dfd6605b02c7ea4e8627d5cea5add6/assets/browser-fetch.js.t#L20

Returning the value rather than throwing it seems to trigger the `success` route in the Ember `invokeCallback` function.

Am I going crazy or is this an issue?!

**Comment by cibernox** [comment]
`fetch` by design only rejects if there is a network issue(being offline p.e). You need to check fir

**Comment by orf** [comment]
So even if the site I'm connecting to is offline, it's still a successful promise?

I understand that it doesn't reject on status codes, but not rejecting on network errors is confusing. Thanks anyway!

**Comment by cibernox** [comment]
On network errors it should reject indeed. If it doesn't it's a bug, but this polyfill is so popular that I don't think that's possible. Are you talking about tests?

**Comment by orf** [comment]
I've got a fiddle here: https://ember-twiddle.com/625abf7d2eff52a579bf2d82c1eceadc?openFiles=controllers.application.js%2C

I am behind a proxy, but still, there seems to be a difference. Can you replicate this?

**Comment by orf** [comment]
Using `1.4.0` results in `true` for all 4 cases. It appears that this change (https://github.com/stefanpenner/ember-fetch/commit/10ea9e15f12723df6e4aaf24a2196cde7944000b) may have introduced it.

**Comment by cibernox** [comment]
Actually I see the error now. I'll see if I can fix it tonight. Essentially we need to return a rejected promise from the second then so we propagate the rejection

**Comment by rwjblue** [comment]
Damn.  Yes, I need to rethrow. :man_facepalming:

**Comment by stefanpenner** [comment]
@rwjblue / @cibernox just a headsup. Master will be a major version bump. So I have created a release-2 branch for all work destined for a 2x release (which this seems part of) 

https://github.com/stefanpenner/ember-fetch/commits/release-2
